sonar.projectKey=renatohvo_sonarcloud-fullcycle-golang
sonar.organization=renatohvo
sonar.host.url=https://sonarcloud.io

sonar.sources=.
sonar.exclusions=**

sonar.tests=.
sonar.tests.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=coverage.out
sonar.coverage.jacoco.xmlReportPaths=build/reports/jacoco/test/jacocoTestReport.xml
