sonar.projectKey=renatohvo_sonarcloud-fullcycle-golang
sonar.organization=renatohvo

sonar.sources=.
sonar.exclusions=**/*_test.go

sonar.tests=.
sonar.tests.inclusions=**/*_test.go
sonar.go.coverage.reportPaths=coverage.out
