sonar.projectKey=renatohvo_sonarcloud-fullcycle-golang
sonar.organization=renatohvo

sonar.sources=src
sonar.exclusions=**/*_test.go

# sonar.tests=src
sonar.tests.inclusions=**/*_test.go

sonar.go.coverage.reportPaths=src/coverage.out
